### ISSUE TITLE
Error trying to configure msstore-cli in my circleci environment

### ISSUE THREAD

**Issue by chordzz** [microsoft/msstore-cli#30]
I am running this command in my circleci pipeline 
`msstore reconfigure --tenantId $TENANT_ID --sellerId $SELLER_ID --clientId $CLIENT_ID --clientSecret $CLIENT_SECRET` 
Even after installing my msstore-cli and confirming that my variables are correct, I keep getting this error.

I am using an ubuntu machine image.

Error:
`
      ...
Use of the Microsoft Store Developer CLI is subject to the terms of the 
Microsoft Privacy Statement: https://aka.ms/privacy
You might need to provide some credentials to call the Microsoft Store APIs.
Let's start!

Unhandled exception: MSStore.API.MSStoreException: Failed to write credential
 ---> MSStore.API.MSStoreException: Failed to write credential: Domain: '137' - Code: '13' - Message: 'Address element “/dev/null” does not contain a colon (:)'
   at MSStore.CLI.Services.CredentialManager.Unix.CredentialManagerUnix.WriteCredentialLinux(String userName, String secret) in /_/MSStore.CLI/Services/CredentialManager/Unix/CredentialManagerUnix.cs:line 289
   --- End of inner exception stack trace ---
   at MSStore.CLI.Services.CredentialManager.Unix.CredentialManagerUnix.WriteCredentialLinux(String userName, String secret) in /_/MSStore.CLI/Services/CredentialManager/Unix/CredentialManagerUnix.cs:line 293
   at MSStore.CLI.Services.CLIConfigurator.ConfigureAsync(Boolean askConfirmation, Nullable`1 tenantId, String sellerId, Nullable`1 clientId, String clientSecret, CancellationToken ct) in /_/MSStore.CLI/Services/CLIConfigurator.cs:line 278
   at MSStore.CLI.Commands.ReconfigureCommand.Handler.InvokeAsync(InvocationContext context) in /_/MSStore.CLI/Commands/ReconfigureCommand.cs:line 78
   at System.CommandLine.NamingConventionBinder.CommandHandler.GetExitCodeAsync(Object returnValue, InvocationContext context)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at MSStore.CLI.Program.<>c.<<Main>b__0_2>d.MoveNext() in /_/MSStore.CLI/Program.cs:line 229
--- End of stack trace from previous location ---
   at System.CommandLine.Hosting.HostingExtensions.<>c__DisplayClass1_0.<<UseHost>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()

Exited with code exit status 1

Exited with code exit status 1

`

**Comment by azchohfi** [comment]
This is probably a missing keyring on the linux environment.
You can try to do the same thing we are doing in our linux CI environment:
https://github.com/microsoft/msstore-cli/blob/09d4c2be9551dbbe4b663cbd43c1e2eb063478bf/.github/workflows/build.yml#L30-L36
