### ISSUE TITLE
Initial configuration failing since v0.1.30

### ISSUE THREAD

**Issue by jakubmeysner** [microsoft/msstore-cli#38]
Initial configuration is failing with the following error since version v0.1.30 (the error did not appear when I tried v0.1.29).

```
Unhandled exception: System.PlatformNotSupportedException: The desktop broker is not directly available in the MSAL package.
Install the NuGet package Microsoft.Identity.Client.Broker and call the extension method .WithBroker(BrokerOptions).
For details, see https://aka.ms/msal-net-wam
   at Microsoft.Identity.Client.PublicClientApplicationBuilder.WithBroker(Boolean enableBroker)
   at MSStore.CLI.Services.TokenManager.MSALTokenManager.InitAppAsync() in /_/MSStore.CLI/Services/TokenManager/MSALTokenManager.cs:line 59
   at MSStore.CLI.Services.TokenManager.MSALTokenManager.SelectAccountAsync(Boolean notMSA, Boolean forceSelection, CancellationToken ct) in /_/MSStore.CLI/Services/TokenManager/MSALTokenManager.cs:line 114
   at MSStore.CLI.Services.CLIConfigurator.GetOrganizationAsync(Configurations config, Boolean forceSelection, CancellationToken ct) in /_/MSStore.CLI/Services/CLIConfigurator.cs:line 389
   at MSStore.CLI.Services.CLIConfigurator.ConfigureAsync(Boolean askConfirmation, Nullable`1 tenantId, String sellerId, Nullable`1 clientId, String clientSecret, String certificateThumbprint, String certificateFilePath, String certificatePassword, CancellationToken ct) in /_/MSStore.CLI/Services/CLIConfigurator.cs:line 76
   at MSStore.CLI.MicrosoftStoreCLI.Handler.InvokeAsync(InvocationContext context) in /_/MSStore.CLI/MicrosoftStoreCLI.cs:line 83
   at System.CommandLine.NamingConventionBinder.CommandHandler.GetExitCodeAsync(Object returnValue, InvocationContext context)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at MSStore.CLI.Program.<>c.<<Main>b__0_2>d.MoveNext() in /_/MSStore.CLI/Program.cs:line 229
--- End of stack trace from previous location ---
   at System.CommandLine.Hosting.HostingExtensions.<>c__DisplayClass1_0.<<UseHost>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

When configured on an older version it seemed to work as expected.

**Comment by azchohfi** [comment]
We are working on a fix, should be available in a few hours.

**Comment by azchohfi** [comment]
Fixed. Should be out in the store soon, but the release is here.
