### ISSUE TITLE
json scaping is too hard to work and fails at certification

### ISSUE THREAD

**Issue by brunvonlope** [microsoft/msstore-cli#70]
## Details

msstore-cli version is 0.1.41.5+425d38bbbe

## Description

I plan to use msstore-cli to automate part of the submission process of 'GIMP (Preview)' MSIX package (https://apps.microsoft.com/detail/9nzvdvp54jmr?hl=en-us&gl=BR)

This is the code that I use to update the submission:

```pwsh
$jsonObject = msstore submission getListingAssets 9NZVDVP54JMR | Select-Object -Skip 5 | ConvertFrom-Json
$jsonObject.'ReleaseNotes' = "haha this is a test"
$final_json = $jsonObject | ConvertTo-Json -Compress
msstore submission updateMetadata 9NZVDVP54JMR $final_json
```

I get this error related to `"` scaping:

```
Unhandled exception: System.Text.Json.JsonException: 'K' is an invalid start of a property name. Expected a '"'. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
 ---> System.Text.Json.JsonReaderException: 'K' is an invalid start of a property name. Expected a '"'. LineNumber: 0 | BytePositionInLine: 1.     
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes) 
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)       
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonTypeInfo`1 jsonTypeInfo)
   at MSStore.CLI.Commands.Submission.UpdateCommand.Handler.PackagedUpdateCommandAsync(IStoreAPIFactory storeAPIFactory, String product, String productId, ILogger logger, CancellationToken ct)
   at MSStore.CLI.Commands.Submission.UpdateCommand.Handler.InvokeAsync(InvocationContext context) in /_/MSStore.CLI/Commands/Submission/UpdateCommand.cs:line 134
   at System.CommandLine.NamingConventionBinder.CommandHandler.GetExitCodeAsync(Object returnValue, InvocationContext context)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at MSStore.CLI.Program.<>c.<<Main>b__0_2>d.MoveNext() in /_/MSStore.CLI/Program.cs:line 229
--- End of stack trace from previous location ---
   at System.CommandLine.Hosting.HostingExtensions.<>c__DisplayClass1_0.<<UseHost>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

I also tried avoid scaping with `$final_json = $jsonObject | ConvertTo-Json -Compress | Foreach-Object {$_ -replace '"','\"'}` but it breaks even further.

How this CLI option is supposed to be used? The Microsoft Learn docs are very laconic and don't provide samples

**Comment by brunvonlope** [comment]
To fix that scaping problems I needed to do a lot of wizardry: 

```pwsh
###Fix submission info against JSON scaping hell
    $final_json = $full_jsonObject | ConvertTo-Json -Compress
    #Fix excessive backslashes
    $final_json = $final_json -replace "\\\\",'\' -replace "\\\\",'\'
    #Scape spaces and new lines
    $final_json = $final_json -replace ' ','\b' -replace '`n','\n'
    #PowerShell converts 'BaseListing' wrongly
    $final_json = $final_json -replace '"{','{' -replace '}"','}'
    $final_json = $final_json -replace '\\"Title\\":\\"GIMP\\b\(Preview\)\\"','\"Title\":\"GIMP\b\r\n(Preview)\"'
    #PowerShell converts 'PlatformOverrides' wrongly
    $final_json = $final_json -replace '""','{}'
    #PowerShell destroys 'Genres' array
    $final_json = $final_json -replace '\"Genres\":\"MultimediaDesign_IllustrationAndGraphicDesign\"','"Genres":["MultimediaDesign_IllustrationAndGraphicDesign"]'
    #PowerShell converts 'Warning' wrongly
    $final_json = $final_json -replace '\"@{','{"' -replace 'Code=','Code":"' -replace ';\\b','","'
    $final_json = $final_json -replace 'Details=','Details":"' -replace '\.}]','."}]'
    #PowerShell destroys 'Languages' array
    $final_json = $final_json -replace '\"Languages\":{}','"Languages":[]'
    $final_json = $final_json -replace '\"Languages\":\"en-US\"','"Languages":["en-US"]'
    #PowerShell destroys 'Capabilities' array
    $final_json = $final_json -replace '\"Capabilities\":{}','"Capabilities":[]'
    $final_json = $final_json -replace 'Capabilities\":\"','Capabilities":["' -replace '\\brunFullTrust\",','","runFullTrust"],'
    ##Scape double quotes
    $final_json = $final_json -replace '"','\"'
    #Fix excessive backslashes again
    $final_json = $final_json -replace "\\\\",'\' -replace "\\\\",'\'
```

So I managed to make an json data that msstore-cli accepts but it fails to be accepted at certification:

![Image](https://github.com/user-attachments/assets/b08be293-8a21-49b8-b8df-0ffa675e8554)

```xml
{
  "Id": "1152921505698712064",
  "ApplicationCategory": "MultimediaDesign_IllustrationAndGraphicDesign",
  "Pricing": {
    "TrialPeriod": "NoFreeTrial",
    "MarketSpecificPricings": {
      "LB": "NotAvailable",
      "EH": "NotAvailable"
    },
    "PriceId": "Free",
    "IsAdvancedPricingModel": false
  },
  "Visibility": "Public",
  "TargetPublishMode": "Immediate",
  "TargetPublishDate": "1601-01-01T00:00:00Z",
  "Listings": {
    "en-us": {
      "BaseListing": {
        "Keywords": [],
        "Description":
"GIMP\b(GNU\bImage\bManipulation\bProgram)\bis\ba\bcross-platform\bimage\beditor\bavailable\bfor\bGNU/Linux,\bmacOS,\bWindows\r\
nand\bmore\boperating\bsystems.\bIt\bis\bfree\bsoftware,\byou\bcan\bchange\bits\bsource\bcode\band\bdistribute\byour\bchanges.\r
\n\r\nWhether\byou\b\r\nare\ba\bgraphic\bdesigner,\bphotographer,\billustrator,\bor\bscientist,\bGIMP\b(Preview)\bprovides\byou\
bwith\bsophisticated\btools\bto\bget\b\r\nyour\bjob\bdone.\bYou\bcan\bfurther\benhance\byour\bproductivity\bwith\bGIMP\b(Preview
)\bthanks\bto\bmany\bcustomization\boptions\band\b3rd\bparty\b\r\nplugins.\r\n\r\nThis\bis\bthe\bofficial\b(preview)\bpackage\bm
aintained\bby\bthe\bGIMP\bteam\bfor\btesting\bpurposes.",
        "Features": [],
        "ReleaseNotes":
"The\bsecond\brelease\bcandidate\bfor\bthe\bupcoming\bGIMP\b3.0.0\bfeatures\ba\blot\bof\bbug\bfixes,\bas\bwell\bas\ba\bfew\nnece
ssary\bcore\bor\bplug-in\bchanges:\n-\bNew\bAPI\bfunctions\bfor\bhandling\blayer\beffects\bfrom\bplug-ins\n-\bMore\bcompat\bPDB\
bprocedures\bremoved\bin\bfavor\bof\bnew\bAPI\n-\bPerceptual\bspace\bfor\blayer\bmode\brenamed\bnon-linear\band\breal\bperceptua
l\bspace\badded\n-\bMajor\bBMP\bsupport\bimprovement\n-\bMany\bbug\bfixes",
        "Images": [
          {
            "FileName": "Captura\bde\bTela\b(115).png",
            "FileStatus": "Uploaded",
            "Id": "1152922700016671095",
            "ImageType": "Screenshot"
          },
          {
            "FileName": "icon_300.png",
            "FileStatus": "Uploaded",
            "Id": "1152922700016698913",
            "ImageType": "Icon"
          }
        ],
        "RecommendedHardware": [],
        "MinimumHardware": [],
        "Title": "GIMP\b\r\n(Preview)"
      },
      "PlatformOverrides": {}
    }
  },
  "HardwarePreferences": [],
  "AutomaticBackupEnabled": false,
  "CanInstallOnRemovableMedia": false,
  "IsGameDvrEnabled": false,
  "GamingOptions": [
    {
      "Genres": [
        "MultimediaDesign_IllustrationAndGraphicDesign"
      ],
      "IsLocalMultiplayer": false,
      "IsLocalCooperative": false,
      "IsOnlineMultiplayer": false,
      "IsOnlineCooperative": false,
      "IsBroadcastingPrivilegeGranted": true,
      "IsCrossPlayEnabled": false,
      "KinectDataForExternal": "Disabled"
    }
  ],
  "HasExternalInAppProducts": false,
  "MeetAccessibilityGuidelines": false,
  "NotesForCertification": "Don\u0027t\bproperly\bsupport\bHiDPI\bor\bWindows\b10\bS.",
  "Status": "PendingCommit",
  "StatusDetails": {
    "Errors": [],
    "Warnings": [
      {
        "Code": "SalesUnsupportedWarning",
        "Details": "The sales resource is no longer supported, and the data you specified for this resource will be ignored. To 
view or edit the sales data for this submission, use the Dev Center dashboard."
      }
    ],
    "CertificationReports": []
  },
  "FileUploadUrl":
"https://ingestionpackagesprod1.blob.core.windows.net/ingestion/8d78f542-c3cc-4f09-b217-f68afa0d3eb5?skoid=6a05eb41-c97a-4f14-a5
ce-d392056c0e00\u0026sktid=975f013f-7f24-47e8-a7d3-abc4752bf346\u0026skt=2024-12-27T17%3A17%3A56Z\u0026ske=2025-01-03T17%3A17%3A
56Z\u0026sks=b\u0026skv=2024-05-04\u0026sv=2024-05-04\u0026se=2024-12-28T17%3A34%3A52Z\u0026sr=b\u0026sp=rwl\u0026sig=LpFdMKJR%2
FCUzfqLDddmxsBYrx8E%2B0E88XU6xPSiVWQo%3D",
  "ApplicationPackages": [
    {
      "FileName": "GIMP.GIMPPreview_3.0.0.0_x64_arm64_bundle.msixupload",
      "FileStatus": "Uploaded",
      "Id": "2000000000084126069",
      "Version": "3.0.0.0",
      "Architecture": "neutral",
      "Languages": [
        "en-US"
      ],
      "Capabilities": [
        "Microsoft.storeFilter.core.notSupported_8wekyb3d8bbwe",
        "runFullTrust"
      ],
      "MinimumDirectXVersion": "None",
      "MinimumSystemRam": "None"
    },
    {
      "FileName": "GIMP.GIMPPreview_3.0.2.0_x64_arm64_bundle.msixupload",
      "FileStatus": "PendingUpload",
      "Id": null,
      "Version": null,
      "Architecture": null,
      "Languages": [],
      "Capabilities": [],
      "MinimumDirectXVersion": "None",
      "MinimumSystemRam": "None"
    }
  ],
  "PackageDeliveryOptions": {
    "PackageRollout": {
      "IsPackageRollout": false,
      "PackageRolloutPercentage": 0,
      "PackageRolloutStatus": "PackageRolloutNotStarted",
      "FallbackSubmissionId": "0"
      "Architecture": null,
      "Languages": [],
      "Capabilities": [],
      "MinimumDirectXVersion": "None",
      "MinimumSystemRam": "None"
    }
  ],
  "PackageDeliveryOptions": {
    "PackageRollout": {
      "IsPackageRollout": false,
      "PackageRolloutPercentage": 0,
      "PackageRolloutStatus": "PackageRolloutNotStarted",
      "FallbackSubmissionId": "0"
    },
      "MinimumDirectXVersion": "None",
      "MinimumSystemRam": "None"
    }
  ],
  "PackageDeliveryOptions": {
    "PackageRollout": {
      "IsPackageRollout": false,
      "PackageRolloutPercentage": 0,
      "PackageRolloutStatus": "PackageRolloutNotStarted",
      "FallbackSubmissionId": "0"
    "PackageRollout": {
      "IsPackageRollout": false,
      "PackageRolloutPercentage": 0,
      "PackageRolloutStatus": "PackageRolloutNotStarted",
      "FallbackSubmissionId": "0"
      "PackageRolloutStatus": "PackageRolloutNotStarted",
      "FallbackSubmissionId": "0"
      "FallbackSubmissionId": "0"
    },
    "IsMandatoryUpdate": false,
    "MandatoryUpdateEffectiveDate": "1601-01-01T00:00:00Z"
  },
  "EnterpriseLicensing": "Online",
  "AllowMicrosoftDecideAppAvailabilityToFutureDeviceFamilies": true,
  "AllowTargetFutureDeviceFamilies": {
    "Desktop": true,
    "Mobile": false,
    "Xbox": false,
  "AllowTargetFutureDeviceFamilies": {
    "Desktop": true,
    "Mobile": false,
    "Xbox": false,
    "Desktop": true,
    "Mobile": false,
    "Xbox": false,
    "Mobile": false,
    "Xbox": false,
    "Xbox": false,
    "Team": false,
    "Team": false,
    "Holographic": false,
    "Holographic": false,
    "7": false
  },
  "FriendlyName": null,
  "Trailers": []
}
```

**Comment by azchohfi** [comment]
This issue is similar to #15, and its going to hugely improved in the next release.

**Comment by brunvonlope** [comment]
According to my tests, the only improvement on the new release regarding Json is that we don't need to use 'Select-Object -Skip 3' anymore. Not sure if this is a "huge" improvement. I still need to manually scape characters and Partner Center doesn't recognize them.

**Comment by azchohfi** [comment]
This should not have anything to do with the CLI itself, as the issue appears to be only related to json parsing. Powershell has the ConvertFrom-Json (specifically with -AsHashtable). I also believe you called the wrong command (you should have used `msstore submission get`).

Here is a working example (I just tested this for a flutter app, but should be the same for other app types):
```
msstore package .
msstore publish --noCommit
$json = msstore submission get $AppId | ConvertFrom-Json -AsHashtable
$json.Listings.'en-us'.BaseListing.ReleaseNotes = 'My release notes'
msstore submission updateMetadata $AppId ($json | ConvertTo-Json -Depth 100) -v
```

**Comment by brunvonlope** [comment]
@azchohfi Ok, I will test in GIMP 3.1.4 release this saturday.

That is off-topic but what is the difference beween `get` and `getListingAssets,` and `update` and `updateMetadata`. The Microsoft Learn documentation is laconic and tells nothing why there is these two options to pull and push submission info.

**Comment by azchohfi** [comment]
The Microsoft Store Developer CLI supports both packaged and unpackaged applications, but most commands it return something quite different depending on the app type.
For packaged applications, `get` and `getListingAssets` call the exact same underlying REST API, but getListingAssets prints only each Listing's BaseListing.
We do need better documentation, and I apologize... We are working internally to get this funded properly so these kinds of issues are taken care of.

ORT the -AsHashtable, that is correct. On PS5.1 you can use System.Web.Extensions, which has a json serializer that works better:
```
Add-Type -AssemblyName System.Web.Extensions
$fromJson = { param($s) $j=New-Object System.Web.Script.Serialization.JavaScriptSerializer; $j.MaxJsonLength=[int]::MaxValue; $j.DeserializeObject($s) }
$toJson   = { param($o) $j=New-Object System.Web.Script.Serialization.JavaScriptSerializer; $j.MaxJsonLength=[int]::MaxValue; $j.Serialize($o) }

msstore package .
msstore publish --noCommit
$j = & $fromJson (msstore submission get $AppId)
$j['Listings']['en-us']['BaseListing']['ReleaseNotes'] = 'My release notes'
msstore submission updateMetadata $AppId (& $toJson $j) -v
msstore submission publish $AppId
```

**Comment by brunvonlope** [comment]
With $toJson we go back to the scaping problem (error log is too big to paste). 

<img width="594" height="282" alt="Image" src="https://github.com/user-attachments/assets/586046d6-e492-4f8e-9b6b-8d658957daa2" />

There is the updated commands we use:

```powershell
## Update submission info
###Get changelog from Linux appdata
$xmlObject = New-Object XML
$xmlObject.Load("desktop\org.gimp.GIMP.appdata.xml.in.in")
$store_changelog = ($xmlObject.component.releases.release[0].description.SelectNodes(".//p | .//li") | ForEach-Object { $text = ($_.InnerText).Trim() -replace '\s*\r?\n\s*', ' '; if ($_.Name -eq 'li') { "- $text" } else { $text } } ) -join "`n"
###Prepare submission info
Add-Type -AssemblyName System.Web.Extensions
$fromJson = { param($s) $j=New-Object System.Web.Script.Serialization.JavaScriptSerializer; $j.MaxJsonLength=[int]::MaxValue; $j.DeserializeObject($s) }
$jsonObject = & $fromJson (msstore submission get $PRODUCT_ID)
$jsonObject['Listings']['en-us']['BaseListing']['ReleaseNotes'] = "$store_changelog"
$toJson   = { param($o) $j=New-Object System.Web.Script.Serialization.JavaScriptSerializer; $j.MaxJsonLength=[int]::MaxValue; $j.Serialize($o) }
msstore submission updateMetadata $PRODUCT_ID (& $toJson $jsonObject) -v
```

[org.gimp.GIMP.appdata.xml.in.txt](https://github.com/user-attachments/files/22044764/org.gimp.GIMP.appdata.xml.in.txt)

**Comment by kswanny** [comment]
@azchohfi I second this bug, not sure if the amount of scraping above is necessarily required but this fix you've presented causes problems with encoding especially for descriptions in other languages.  I'll try to explain as best I can.

```
msstore package .
msstore publish --noCommit
$json = msstore submission get $AppId | ConvertFrom-Json -AsHashtable
$json.Listings.'en-us'.BaseListing.ReleaseNotes = 'My release notes'
msstore submission updateMetadata $AppId ($json | ConvertTo-Json -Depth 100) -v
msstore submission publish $AppId
```

When you use `ConvertFrom-Json`, the original listings often contain unescaped Unicode (as returned by `msstore submission get $AppId`). This makes it tricky to update metadata without breaking formatting in fields like descriptions or keywords.

You can replicate this by setting your `en-us` description in the the UI as something like

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

================================================================== 
FEATURE HIGHLIGHTS
================================================================== 

- My feature
- Another awesome feature
- Some more features
- Some crazy cool features

Terms and conditions
- One https://exampleterms.com

```
Then try
`$rawJson = msstore submission get $AppId`
`$json = msstore submission get $AppId | ConvertFrom-Json -AsHashtable`

If you compare `$rawJson`  to `$json` it will have a description that looks something like:
```
\n\n==================================================================\u00A0\nFEATURE 
HIGHLIGHTS\n==================================================================\u00A0\n\n-

Some more stuff etc
```
Where $json will have (on two lines)

```
================================================================== 
FEATURE
HIGHLIGHTS
================================================================== 
```

TO further validate this just update the metadata and check the partner center submission and it will look different in the UI.

`msstore submission updateMetadata $AppId ($json | ConvertTo-Json -Depth 100) -v`

**Comment by knangunu** [comment]
@brunvonlope @kswanny The reason for $json to be on two lines is due the line limit. Reducing the line length should make it on a single line. Could and try this in the description and see if it works.
========================
FEATURE HIGHLIGHTS
========================

And for the update metadata, you could also follow the approach of reading the metadata from the file. Could you try this and check if this helps.

> $json = Get-Content -Path "path\to\metadata.json" | ConvertFrom-Json -AsHashtable
> msstore submission updateMetadata 9NP0T3QQXL70 ($json | ConvertTo-Json -depth 100) -v

**Comment by brunvonlope** [comment]
I will be closing since there is not bug on msstore-cli side (while documentation of PowerShel v6+ implicit dependency would be nice on Microsoft Learn)
